transactions:
  - seed: "blush roast crime veteran comic useful explain session exercise gold shoe cross"
    contract_adress: "0x7e624fa0e1c4abfd309cc15719b7e2580887f570"
    recipient_address: "0x11c306924C55E59e639E9ECD7B4A6D81B22EC739"
    amount: 1
    decimals: 18

#  - seed: ""
#    spender_address: ""
#    amount: 1
#    decimals: 18